Artist.create!([
  {artist_name: "Gabe Barham", artist_band: "Sleeping With Sirens", artist_img: "http://www.chriseddie.com/truth/img/artists/03.jpg", artist_hero_img: "http://www.chriseddie.com/truth/img/artists/gbarham-hero.jpg", artist_bio: "Gabe Barham is the drummer of Sleeping with Sirens, an American post-hardcore band from Orlando, Florida currently residing in Grand Rapids, Michigan. The band was formed in 2009 by members of For All We Know, Broadway, and We Are Defiance. They are currently signed to Rise Records and have released two full-length albums and an acoustic EP, If You Were a Movie, This Would Be Your Soundtrack, which was released on June 26, 2012. The group is known primarily for the versatility of vocalist Kelin Quinn's tenor leggier vocal range.\r\n\r\nIn January 2013 the band will enter the studio to record their follow up to Let's Cheers to This with an estimated release date of mid-2013. On 23rd April 2013, the band released a new single called Low and the new album title Feel that will be in stores June 4th, 2013. In support of the new album, the band will be playing main stage at Warped Tour 13.\r\n\r\nNow three years into their existence, the post-hardcore quintet Sleeping With Sirens continue to evolve and mature as artists, gradually shaping their unmistakable blend of fury and melody into a sound that's wholly their own. The band's new five-song acoustic EP, If You Were a Movie, This Would Be Your Soundtrack, presents another crucial step on the band's ongoing journey toward their sonic destiny.", artist_bio_src: "https://en.wikipedia.org/wiki/Sleeping_with_Sirens", kit_specs: "22x18x, 16x16, 13x9", kit_material: "8-Ply Maple", kit_finish: "Custom designed \"Uncle Sam\" Metallic Wrap", kit_img: "http://www.chriseddie.com/truth/img/builds/2015-07-18.jpg", social_inst: "https://www.instagram.com/gabebarham/", social_fb: "https://www.facebook.com/profile.php?id=100010841283310", social_twit: "https://twitter.com/gabebarham"},
  {artist_name: "Ryan Seaman", artist_band: "Falling in Reverse", artist_img: "http://www.chriseddie.com/truth/img/artists/01.jpg", artist_hero_img: "", artist_bio: "In 2002, Ryan got his first touring opportunity to play on the Vans Warped Tour, drumming for Lookout Records artist The Eyeliners.[1] He toured with them again later that year on the No Use For A Name/Yellowcard/The Eyeliners/Gob/Slick Shoes tour.\r\n\r\nIn 2005, Ryan joined the band of post-hardcore I Am Ghost,[2] recording some tracks for their debut album, Lovers' Requiem, released in 2006.[3] In April 2009 he joined the pop rock band The Bigger Lights,[4] participating in two albums and an EP,[5][6] leaving the band in May 2011. He has also participated as a drummer on tour, with artists or bands such as Fairview, Kiev, Jeffree Star, Electric Valentine, The Brobecks,[7] Madcap, Love Equals Death, Good Knives, Vanna, Kill Paradise, My Favorite Highway, William Tell, Kaitee Page, Alexa Wilkinson, The Eyeliners, Matchbook Romance and Aiden.[8]\r\n\r\nIn late May 2011, Seaman officially joined the post-hardcore band, Falling in Reverse,[9][10] replacing LoveHateHero drummer, Scott Gee. The band released their first album, The Drug in Me Is You on July 26, although on the album his name appears in the credits,[11] Ryan did not participate in the album at the time. Despite this Ryan has appeared in many of their videos, For example; The Drug in Me Is You (June 2011),[12] I'm Not a Vampire (October 2011),[13] \"Raised By Wolves\" (February 2012),[14] \"Good Girls, Bad Guys\" (June 2012).[15]", artist_bio_src: "Wikipedia", kit_specs: "22x18x, 16x16, 13x9", kit_material: "Maple", kit_finish: "Pearl", kit_img: "http://chriseddie.com/truth/img/builds/2015-07-18.jpg", social_inst: "instagram.com", social_fb: "facebook.com", social_twit: "twitter.com"},
  {artist_name: "Mike Fuentes", artist_band: "Pierce the Veil", artist_img: "http://chriseddie.com/truth/img/artists/02.jpg", artist_hero_img: "", artist_bio: "Michael Christopher \"Mike\" Fuentes (born December 14, 1984 in San Diego) is an American musician from San Diego, California. He is the drummer for the post-hardcore band Pierce the Veil alongside his older brother Vic Fuentes.[2] Fuentes was the percussionist for the metal supergroup Isles & Glaciers. He has more recently began a hip hop solo project under the stage name MikeyWhiskeyHands in which he raps on instrumentals produced by Pierce the Veil's bassist Jaime Preciado. Fuentes signed to Velocity Records in March 2012.", artist_bio_src: "Wikipedia", kit_specs: "13×8, 16×16, 18×16, 24×16", kit_material: "Maple", kit_finish: "Custom 4 graphic Harry Potter glass wrap. Chrome hardware, 50% offset lugs, mounted floor tom legs.", kit_img: "http://chriseddie.com/truth/img/potter.jpg", social_inst: "instagram.com", social_fb: "facebook.com", social_twit: "twitter.com"}
])
Drum.create!([
  {drumTitle: "Grey Sparkle", drumSize: "24x16, 16x16, 12x8", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-12-02.jpg", drumPrice: "$3,450", drumCustomer: "Chris Eddie", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "8-ply maple, grey sparkle wrap, aged white pearl pinstripe"},
  {drumTitle: "Flat Black w/ Red Stripes", drumSize: "26x16, 18x16, 16x15, 13x9", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-11-14.jpg", drumPrice: "$3,000", drumCustomer: "Wylie Foster", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "8-ply maple, silver walnut vertical veneer, beavertail lugs"},
  {drumTitle: "Marvel Madness", drumSize: "24x20, 12x7, 16x16", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-11-19.jpg", drumPrice: "$6,000", drumCustomer: "Jeremy Gros", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "10 ply maple, custom Marvel theme graphics over pearl, black nickel hardware, custom wood distressed badges, logo graphic bass head"},
  {drumTitle: "Blue Pearl Stripe", drumSize: "22x16, 16x16, 12x8", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-11-13.jpg", drumPrice: "$3,200", drumCustomer: "Aaron Rosa", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "8 ply birch, flat black with turquoise ripple stripe, relic hardware, fiberskyn head, relic bass hole ring"},
  {drumTitle: "Brown Satin Snare", drumSize: "14x8", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-12-10.jpg", drumPrice: "$400", drumCustomer: "Nicholas Taylor", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "10 ply maple, brown satin, gold hardware"},
  {drumTitle: "White Brass", drumSize: "14x10", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-12-04.jpg", drumPrice: "$500", drumCustomer: "Matt Marquez", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "1 mil brass with bead, black nickel, black tension rods"},
  {drumTitle: "Grey Sparkle", drumSize: "24x20, 12x7, 16x16", drumPhoto: "http://chriseddie.com/truth/img/builds/2015-07-18.jpg", drumPrice: "$3,200", drumCustomer: "Geoff Barrios", drumCustomerSocial: "http://instagram.com/chriseddie", drumDetails: "Grey sparkle with aged white pinstripe"}
])
